"use client"
import { Inter } from "next/font/google";
import Footer from "../app/component/footer"
import { FaSearch } from "react-icons/fa";
import Link from 'next/link';
import { url } from "next/link"
import Head from 'next/head';
import Header from "../pages/component/header/index"



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {





  return (
    <html>
      <body id="top" className={inter.className} >
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossOrigin="anonymous" />

        <div className="container-fluid p-0">
          <div className="  position-fixed top-0 w-100 opacity-75 bg-blue-600" style={{ height: "5rem", backgroundImage: 'url("/public/snapp.webp")', zIndex: 1000 }}>


            <div className="container mt-3"  >
              <header>
                <div className="hstack gap-3 w-100">
                  <div className="p-2">
                    <button><FaSearch className='text-white justify-center content-center' /></button>




                  </div>

                  <div className="text-white p-2">
                    <Link href={"/login"} className='justify-center content-center Link' id="support" style={{ textDecoration: "none", color: "white" }}>پشتیبانی</Link>
                  </div>

                  <div className="text-white p-2">
                    <Link href={"/about"} className='justify-center content-center Link' id="about" style={{ textDecoration: "none", color: "white" }}>درباره ما</Link>
                  </div>

                  <div className="text-white p-2">
                    <Link href={"/service"} className='justify-center content-center Link' id="service" style={{ textDecoration: "none", color: "white" }}>خدمات</Link>
                  </div>

                  <div className="text-white p-2">
                    <Link href={"/contact"} className='justify-center content-center Link' id="contact" style={{ textDecoration: "none", color: "white" }}>ارتباط با ما</Link>
                  </div>

                  <div className="text-white p-2">
                    <Link href={"/"} className='justify-center content-center Link' id="home" style={{ textDecoration: "none", color: "white" }}>خانه</Link>
                  </div>



                  <div className="flex p-2 ms-auto">
                    <span className='pr-1 text-white opacity-80 justify-center ml-3 container-fluid'>نوآوری در فناوری هوشمندی </span><br />
                  </div>


                  <div className="flex p-2">
                    <img src="/logo-ebtekar.svg" className='rounded-3xl img-fluid justify-center content-center mr-7' alt="Logo Comapny" height={150} width={150} />
                  </div>
                </div>
              </header>
              <br />






            </div>


          </div>



          
          <a href="#top" className="mr-4 mb-1 back-to-top">▲</a>



















          <br /><br /><br />
          {children}
          <br />
          <Footer />
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossOrigin="anonymous"></script>
      </body>
    </html>
  );
}
